### ISSUE TITLE
Update to BrXM 14.latest?

### ISSUE THREAD

**Issue by mxdrenthe** [bloomreach-forge/brut#10]
Would love to see this plugin getting updated to the latest version of the BrXM product

**Comment by jeroenhoffman** [comment]
Hi Michel, 
Version 3.0.1 should be compatible with all BrXM 14.x versions. We don't create new plugin versions with every minor brXM release, unless really necessary. Is there something not working out when using this on 14.6.0?
Cheers, Jeroen
