### ISSUE TITLE
BRUT in Bloomreach 13.3.0

### ISSUE THREAD

**Issue by behzadkh** [bloomreach-forge/brut#3]
Dear Baris,
I am gonna use BRUT in BloomReach version 13.3.0.
so is it possible to use in 13.3.0 version?
and I made a try but the dependencies could not resolve in maven repository.
I added below two dependencies in pom.xml in component module in site module.
`
```
    <dependency>
      <groupId>org.bloomreach.forge.brut</groupId>
      <artifactId>brut-components</artifactId>
      <version>2.0.0</version>
      <scope>test</scope>
    </dependency>
```
```

    <dependency>
      <groupId>org.bloomreach.forge.brut</groupId>
      <artifactId>brut-resources</artifactId>
      <version>2.0.0</version>
      <scope>test</scope>
    </dependency>
```
`

please correct me where I was wrong.
thanks.

**Comment by mxdrenthe** [comment]
Have you added to your root pom.xml:
```
<repositories>
  ...
  <repository>
    <id>hippo-forge</id>
    <name>Hippo Forge Maven 2 Repository</name>
    <url>https://maven.onehippo.com/maven2-forge/</url>
  </repository>
<repositories>
```

**Comment by bcanvural** [comment]
@behzadkh I didn't test brut on 13.3. Current version is 13.1. I"m in the process of upgrading to 13.4. The main hiccup seems to be the dynamic beans feature which was introduced in 13.2. I'm thinking there might be some issues in 13.3 because of that too.

**Comment by bcanvural** [comment]
This upgrade has been done, closing this.
